# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 982e45ea31a4f1a7d7fff9cc08dcab6feb655d214032029a182892794fef46cf1b93b2b9802edca4d147443d1436faab5eda9a29c854859f0d967154f6058921

test:
  secret_key_base: cb16581a9e067bff9e8372f846ae7c7e0542e88277700ce3e0a508238c6d06d44291cbea867d311e3586ec953cd5e095829a69505dcba290a122170588a91e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
